### ISSUE TITLE
Global log file not writeable by all users

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/clef#138]
The global log file was not writeable by `hh5` (it was owned by `hh5_w`)

https://track.nci.org.au/browse/CWSHELP-1410

I made a new one and did some ACL jiggery pokery to make it writeable.

Perhaps this should be enclosed in a `try/except` block and not log if it isn't accessible.

**Comment by paolap** [comment]
I think this happened because I moved the file there from ua8, adjusted the permissions and forgot to change the group.
We want the log because it's the only way to get stats, they should definitely have access to hh5 to use clef.
So if we put a try/except I need to find a way to get notified.
We've done this before for ua8 and it worked fine, I moved it here so there wasn't an extra group to join for users. I'll pay attention to this at the start of next month but if it works fine then there's no reason to.

**Comment by paolap** [comment]
This doesn't appear to be an issue anymore
